[fmt]
line_length = 120

[profile.default]
bytecode_hash = "none"
optimizer_runs = 1000000
solc = "0.8.13"
fs_permissions = [{ access = "write", path = "./logs/"}]

[profile.intense]
fuzz_runs = 10000

